### ISSUE TITLE
No Azure DevOps organization can't accept 

### ISSUE THREAD

**Issue by zer0big** [microsoft/vscode-deploy-azure#70]
Hello, teams.

I think this extension is very helpful and nice.

I've been trying to configure "Deploy to Azure Configure CI/CI Pipeline"
After choosing the target of Azure subscription and web app, I can't proceed at all. 
Any organization of my Azure DevOps can't accept like below.

![image](https://user-images.githubusercontent.com/38598117/78469340-25e95780-775b-11ea-827a-3c4a1337859f.png)

- My Azure DevOps Organization : https://dev.azure.com/zerobig-devops/

I've tried another organization also, but the result was the same.
How can I solve this issue?

**Comment by bishal-pdMSFT** [comment]
@zer0big looks like the extension is asking you to create a new ADO organization. Since the org with that name already exists, it is showing you an error. You can choose a different name.
It tries to create a new ADO organization when the local workspace which you have opened is:
1. either not a git repo
2. or it it a git repo but does not have any remote tracking set.
In both cases, the extension will try to create a new ADO organization and repo and then push your code to that.

**Comment by anuragc617** [comment]
Closing this issue as there is no active conversation.
